### ISSUE TITLE
unable to run user-services and config-service outside docker?

### ISSUE THREAD

**Issue by sridhar1982** [kbastani/spring-cloud-microservice-example#6]
I am trying to start user-service and discovery-service as standalone services in my local box served at different ports instead of running them in docker containers.

The reason behind running them as standalone services is we want to deploy them as standalone microservices in production. 

**1.   I started the discovery-service**

`cd spring-cloud-microservice-example/discovery-microservice`

`mvn clean spring-boot:run`

The eureka server started correctly from logs below

```
2015-08-18 14:46:12.139  INFO 2305 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2015-08-18 14:46:12.178  WARN 2305 --- [       Thread-2] c.n.eureka.cluster.PeerEurekaNodes       : The replica size seems to be empty. Check the route 53 DNS Registry
2015-08-18 14:46:12.237  INFO 2305 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8761 (http)
2015-08-18 14:46:12.239  INFO 2305 --- [           main] services.Application                     : Started Application in 4.198 seconds (JVM running for 6.99)
2015-08-18 14:48:42.257  INFO 2305 --- [       Thread-2] c.n.e.PeerAwareInstanceRegistryImpl      : Got 1 instances from neighboring DS node
2015-08-18 14:48:42.257  INFO 2305 --- [       Thread-2] c.n.e.PeerAwareInstanceRegistryImpl      : Renew threshold is: 1
2015-08-18 14:48:42.258  INFO 2305 --- [       Thread-2] c.n.e.PeerAwareInstanceRegistryImpl      : Changing status to UP
2015-08-18 14:48:42.259  INFO 2305 --- [       Thread-2] c.n.eureka.AbstractInstanceRegistry      : Finished initializing remote region registries. All known remote regions: []
2015-08-18 14:48:42.267  INFO 2305 --- [       Thread-2] e.s.EurekaServerInitializerConfiguration : Started Eureka Server
```

**2.    I started the config-service**

`cd  spring-cloud-microservice-example/config-microservice`

`mvn clean spring-boot:run`

<b> Error: Can't get a response from http://discovery:8761/eureka/apps/CONFIGSERVER </b>

```
2015-08-18 14:46:38.118  WARN 2322 --- [ost-startStop-1] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://discovery:8761/eureka/apps/
org.apache.http.conn.ConnectTimeoutException: Connect to discovery:8761 timed out
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.jar:4.5]
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170) ~[jersey-apache-client4-1.11.jar:1.11]
	... 88 common frames omitted
Wrapped by: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.ConnectTimeoutException: Connect to discovery:8761 timed out
```

**3.   I started the user-service**

`cd spring-cloud-microservice-example/users-microservice`

`mvn clean spring-boot:run`

<b> Error: Can't get a response from http://discovery:8761/eureka/apps/USER </b>

```
2015-08-18 14:56:49.839  WARN 2391 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : Can't get a response from http://discovery:8761/eureka/apps/CONFIGSERVER
org.apache.http.conn.ConnectTimeoutException: Connect to discovery:8761 timed out
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117) ~[httpclient-4.5.jar:4.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.jar:4.5]
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170) ~[jersey-apache-client4-1.11.jar:1.11]
	... 20 common frames omitted
Wrapped by: com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.ConnectTimeoutException: Connect to discovery:8761 timed out
```

**Comment by kbastani** [comment]
Please move this question to Stackoverflow.
