### ISSUE TITLE
docker container not responding with microservices

### ISSUE THREAD

**Issue by sridhar1982** [kbastani/spring-cloud-microservice-example#7]
I followed the steps provided here
http://www.kennybastani.com/2015/07/spring-cloud-docker-microservices.html

I got the dockers containers up.

![screen shot 2015-08-18 at 3 27 37 pm](https://cloud.githubusercontent.com/assets/4313954/9344516/1623313c-45be-11e5-8967-eb4716e627a6.png)

However, I see the following error in logs

```
Can't get a response from http://discovery:8761/eureka/apps/
config_1         | java.net.ConnectException: Connection refused
config_1         | 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_66-internal]
config_1         | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_66-internal]
config_1         | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_66-internal]
config_1         | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_66-internal]
config_1         | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66-internal]
config_1         | 	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66-internal]
config_1         | 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.jar!/:4.5]
config_1         | 	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170) ~[jersey-apache-client4-1.11.jar!/:1.11]
config_1         | 	... 20 common frames omitted
```

And 

```
open $(echo \"$(echo $DOCKER_HOST)/movie\"|
            \sed 's/tcp:\/\//http:\/\//g'|
            \sed 's/[0-9]\{4,\}/10000/g'|
            \sed 's/\"//g')
```

opened this url `http://127.0.0.1:8761/`. But the webpage is not available.

I am using dockers on Mac.

**Comment by kbastani** [comment]
Docker doesn't have a DNS meaning it can't resolve hosts to the IP of the container running discovery service. You need to use IPs or link the docker containers. See their documentation. Also, move this to Stackoverflow.

**Comment by sridhar1982** [comment]
how does in your blog you were able to get it working but when I follow the same steps in my local machine, I get IP issue of container running discovery service.  I have posted the question here: https://stackoverflow.com/questions/32086410/unable-to-run-spring-cloud-microservices-with-eureka-using-dockers.  I hope you can help me out.
